onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  ipx@>=2.0.0-0 <2.1.1: '>=2.1.1'
  tmp@<=0.2.3: '>=0.2.4'
  devalue@<5.3.2: '>=5.3.2'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  nuxt@>=3.6.0 <3.19.0: '>=3.19.0'
